version: "2.0"

services:
  memorygame:
    image: jungpilyu/memorygame
    expose:
      - port: 80
        as: 80
        to:
          - global: true

profiles:
  compute:
    memorygame:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage:
          size: 2Gi

placement:
  lagrange:
    pricing:
      memorygame:
        denom: uakt
        amount: 10000

deployment:
  memorygame:
    lagrange:
      profile: memorygame
      count: 1
