version: "2.0"

services:
  tetris:
    image: uzyexe/tetris
    expose:
      - port: 80
        to:
          - global: true

profiles:
  compute:
    tetris:
      resources:
        cpu:
          units: 1.0
        memory:
          size: 512Mi
        storage:
          size: 512Mi

placement:
  lagrange:
    pricing:
      tetris:
        denom: uakt
        amount: 10000

deployment:
  tetris:
    lagrange:
      profile: tetris
      count: 1
